name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      # This block is copied from https://github.com/neovim/nvim-lspconfig, great work!
      - run: date +%F > todays-date
      - name: Restore cache for today's neovim nightly.
        uses: actions/cache@v2
        with:
          path: _neovim
          key: ${{ runner.os }}-nightly-${{ hashFiles('todays-date') }}
      - name: Setup from neovim nightly
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64

      - name: "Run test script"
        run: ./scripts/test.sh
